### ISSUE TITLE
Add iOS 14 changes per WWDC 2020

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/privacyflash-pro#18]
At WWDC 2020 Apple announced some new privacy features in iOS 14, which we should account for.

- There seems to be a **new location API** that allows apps to only access the approximate location of a device within a certain radius.
- Apps need to have **permission to track users across devices**. Maybe, this will be a new permission.
- App **developers will be asked to provide which permissions (and other resources?) their apps are using**. As I understand, this information has to be provided by the developer manually and will be displayed on an app's App Store page in a nutrition label-like format. I do not think that we need to implement any new features here. (Maybe, we can think about generating a label that developers can create and paste in Apple's form. This would be essentially a subset of what we analyze. So, in addition of generating a privacy policy, developers could also generate the label.) 

All in all, these news are making a pretty good case for PrivacyFlash Pro.

(cc'ing @kalicki1)

**Comment by SebastianZimmeck** [comment]
And while we are at it, we should also add the [ExposureNotification](https://developer.apple.com/documentation/exposurenotification) API (and possibly some other remaining ones, e.g., [Notifications](https://developer.apple.com/notifications/)).

**Comment by SebastianZimmeck** [comment]
There is a WWDC [Build Trust Through Better Privacy video](https://developer.apple.com/videos/play/wwdc2020/10676/) available. Here are some of the important parts:

- Limited photos library access: app can only be given access to one photo. `PHPicker` replaces `UIImagePickerController`. Just as `UIImagePickerController`, `PHPicker` does not require any permission access.
- Instead of requiring access to all contacts on a device, an app can ask for only for one contact (via autocomplete). This request does not require contacts permission.
- Apps should consider using new approximate location API
- Encrypted DNS now natively available
- Starting in Fall 2020, developers have to provide answers to a privacy questionnaire on the App Store. We should definitely include functionality for this in PrivacyFlash Pro.
- There will be a new `Nearby Interaction API`
- Permission is required for tracking users across devices. This is done via the `AppTrackingTransparency` API. An  `NSUserTrackingUsageDescription` has to be provided. `AppTrackingTransparency` should be called each time before the IDfA is used.
- `SKAdNetwork` can be adopted by ad networks in their SDKs to prevent tracking
- Also, from the keynote it is my understanding that iOS apps can run natively on the new Mac architecture. So, iOS apps will likely become more prevalent and, thus, we will cover apps there as well.

**Comment by SebastianZimmeck** [comment]
Per our discussion, @rgoldstein01 will check whether there are any major API changes that we should include in the upcoming  release next week. In particular, the `AppTrackingTransparency` API may be worthwhile to include.

**Comment by rgoldstein01** [comment]
Opened branch issue-18.

**Comment by rgoldstein01** [comment]
I will also add the documentation to the yaml file. But here is what I have found about iOS 14:

App Tracking Transparency:
(https://developer.apple.com/documentation/apptrackingtransparency)

`NSUserTrackingUsageDescription` should be in the plist
`requestTrackingAuthorization(completionHandler:)` is a method
`ATTrackingManager` is a class
A few other methods: `trackingAuthorizationStatus` and `AuthorizationStatus`

Here is a list of all the developer changes to iOS14 : https://developer.apple.com/ios/whats-new/
Going through the other changes, nothing else seems particularly relevant. So, I will add the UserTracking commands, although I am not sure exactly what permission to file it under. It just seems to be general "tracking"

We could also consider adding their augmented reality kit, which is new to iOS14, as its own permission. You can read more about it here: https://developer.apple.com/documentation/arkit/. To use it, you have to still get permission from permissions we do detect, like, say camera. However, I can definitely see how an argument could be made that AR presents an even more invasive, and privacy-sensitive situation that should be included in a privacy policy.

Edit: Updated that this App Tracking Transparency framework does not seem to be directly tied to location.

**Comment by SebastianZimmeck** [comment]
Per @rgoldstein01's suggestion in a discussion we had, we can also replace IDFA detection with the new tracking permission.

**Comment by SebastianZimmeck** [comment]
OK, the changes from IDFA to TRACKING are now in the main branch. @rgoldstein01, as discussed, could you run WorkoutWithFriends one more time on that version? If everything works, I will create a new release version.

**Comment by rgoldstein01** [comment]
With the changes, it appears WorkoutWithFriends ran a smooth analysis. Attaching a screenshot of the permission results, which matches up with how it was analyzing the app previously. Nice job, everyone!

![New Screen Shot Name 2021-03-01 at 9 40 45 AM](https://user-images.githubusercontent.com/43993790/109512785-730ca100-7a72-11eb-9aed-9920df80648d.jpg)

**Comment by SebastianZimmeck** [comment]
Excellent! Thank you, @rgoldstein01! I will go ahead and prepare the release.
